with import <nixpkgs> {}; [
  aspell
  aspellDicts.en
  cacert
  haskellPackages.Agda
  haskellPackages.cabal-install
  haskellPackages.cabal2nix
  haskellPackages.darcs
  haskellPackages.ghc
  haskellPackages.idris
  haskellPackages.purescript
  irssi
  jshon
  mercurial
  nix
  nix-prefetch-scripts
  nix-repl
  nixopsUnstable
  offlineimap
  pandoc
  socat
  tree
  weechat
  wget
  youtube-dl
]
