set nocompatible

" Must set global tabstop/shiftwidth/expandtab before 'syntax on'
" because 'syntax on' triggers FileType detection which runs ftplugin files.
" If these are set after, they can clobber buffer-local ftplugin settings.
set expandtab
set tabstop=2
set shiftwidth=0 " use tabstop

set termguicolors
syntax on
colorscheme inl
set background=light

if has("gui_running")
  set guioptions=
  set guifont=Monospace\ 10
  set guicursor+=a:blinkon0
endif

set hlsearch
set incsearch
set nowrap
set number
set ruler
set showcmd
set showmatch
set wildmenu

set laststatus=1
set signcolumn=yes

set backspace=indent,eol,start
set path=.,,**

set wildignore+=*/.git/*

setglobal tags=./tags;

let g:mapleader = " "
let g:maplocalleader = "\\"

nnoremap - :e %:h<CR>
nnoremap <F5> :make<CR>
nnoremap <Leader>/ :nohlsearch<CR>

set mouse=a

if !has('nvim')
  if has("autocmd")
    filetype plugin indent on
    let g:c_syntax_for_h = 1
  endif
  runtime vimrc.vim
  runtime functions.vim
endif
