set nocompatible

set termguicolors
syntax on
colorscheme inl
set background=light

if has("gui_running")
  set guioptions=
endif

set expandtab
set hlsearch
set incsearch
set nowrap
set number
set ruler
set showcmd
set showmatch
set wildmenu

set laststatus=1
set shiftwidth=0 " use tabstop
set signcolumn=yes
set tabstop=2

set backspace=indent,eol,start
set path=.,,**

set wildignore+=*/.git/*

setglobal tags=./tags;

if has("autocmd")
  filetype plugin indent on

  let g:c_syntax_for_h = 1
endif

let g:mapleader = " "
let g:maplocalleader = "\\"

nnoremap - :e %:h<CR>
nnoremap <F5> :make<CR>
nnoremap <Leader>/ :nohlsearch<CR>

set mouse=a

if !has('nvim')
  runtime vimrc.vim
  runtime functions.vim
endif

set exrc
set secure
